routes/web.php
<?php

use App\Model\Admin;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Spatie\Activitylog\Models\Activity;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// dd(Auth::guard('admin')->check());
// 




Route::get('/', function () {

    return Activity::all()->last();


    // Admin::create([
    //     'name' => 'faraz',
    //     'email' => 'admin@gmail.com',
    //     'password' => Hash::make(123456789),
    // ]);

    // User::create([
    //     'nick_name' => 'ali reza',
    //     'mobile' => '09357589031',
    //     'gender' => 1,
    //     'password' =>Hash::make(123456)
    // ]);
    return view('welcome');
});


// Auth::routes();

Route::namespace('Auth')->group(function () {

    // activity()->log('Look mum, I logged something')->su;

    Route::get('/admin/login', 'LoginController@showAdminLoginForm')->name('admin.login.form');
    Route::get('/user/login', 'LoginController@showUserLoginForm')->name('user.login.form');
    Route::get('/office/login', 'LoginController@showOfficeLoginForm')->name('office.login.form');

    // Route::get('/user/signup', 'RegisterController@showRegistrationForm')->name('user.signup.form');

    Route::post('/admin/login', 'LoginController@adminLogin')->name('admin.login');
    Route::post('/user/login', 'LoginController@userLogin')->name('user.login');
    Route::post('/office/login', 'LoginController@officeLogin')->name('office.login');

    Route::get('/admin/logout', 'LoginController@adminLogout')->name('admin.logout');
    Route::get('/user/logout', 'LoginController@userLogout')->name('user.logout');
    Route::get('/office/logout', 'LoginController@officeLogout')->name('office.logout');

    Route::get('/office/signup', 'RegisterController@showOfficeRegistrationForm')->name('office.signup');

    // Route::post('/register/admin', 'RegisterController@createAdmin');
    Route::post('/signup', 'RegisterController@register')->name('user.signup');
    Route::post('/office/signup', 'RegisterController@officeRegister')->name('office.signup');


    Route::get('/password/reset', 'ResetPasswordController@showResetForm')->name('password.request');
    Route::post('/password/update', 'ResetPasswordController@reset')->name('password.update');

    Route::get('/token/reset/{mobile}', 'ResetPasswordController@showTokenForm')->name('password.reset.token');
    Route::post('/token/update', 'ResetPasswordController@tokenConfirmed')->name('password.update.token')->middleware('throttle:5|1');



    // Route::view('/home', 'home')->middleware('auth');

    // Route::view('/admin/dashboard', 'admin')->name('admin.');
    // Route::view('/writer', 'writer');


});


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('authDefaultDriver')->group(function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::get('/setting', 'AdminController@setting')->name('setting');
    Route::post('/reset', 'AdminController@resetPassword')->name('password.reset');

    Route::resource('user', 'UserController');
    Route::get('users', 'UserController@showDataTable')->name('user.list');

    Route::get('financial/all', 'AdminController@financialAll')->name('financial.all');

    Route::get('financial/success', 'AdminController@financialSuccess')->name('financial.success');
    Route::get('financial/success/list', 'AdminController@showDataTableFinancialSuccess')->name('financial.success.list');

    Route::get('financial/fail', 'AdminController@financialFail')->name('financial.fail');
    Route::get('financial/fail/list', 'AdminController@showDataTableFinancialFail')->name('financial.fail.list');

    Route::get('alert/index', 'AlertController@index')->name('alert.index');
    Route::get('alert/list', 'AlertController@showDataTableAlert')->name('alert.list');
    Route::get('alert/create', 'AlertController@create')->name('alert.create');
    Route::post('alert/store', 'AlertController@store')->name('alert.store');
    Route::get('alert/destroy/{alert}', 'AlertController@destroy')->name('alert.destroy');

    Route::resource('admins', 'AdminManagerController');
    Route::get('admins-list', 'AdminManagerController@showDataTable')->name('admins.list');

    Route::get('admins/permission/{admin}', 'AdminManagerController@permission')->name('admins.permission');
    Route::post('admins/permission/{admin}', 'AdminManagerController@permissionUpdate')->name('admins.permission');

    Route::get('reports', 'ReportController@index')->name('report.index');
    Route::get('report-list', 'ReportController@showDataTable')->name('report.list');

    Route::get('blocks', 'BlockController@index')->name('block.index');
    Route::get('block-list', 'BlockController@showDataTable')->name('block.list');

    Route::get('admin/blocks', 'BlockController@adminBlockIndex')->name('admin.block');
    Route::get('admin/block-list', 'BlockController@adminBlockShowDataTable')->name('admin.block.list');
    Route::get('admin/block/delete/{user}', 'BlockController@adminBlockDelete')->name('admin.block.delete');

    Route::post('admin/blocks/add/{user}', 'BlockController@adminBlockAdd')->name('admin.block.add');

    Route::resource('package', 'PackageController');


    Route::get('config', 'ConfigController@index')->name('config');
    Route::post('config', 'ConfigController@update')->name('config.update');


    Route::get('ticket/index', 'TicketController@index')->name('ticket.index.list');
    Route::get('ticket/list', 'TicketController@showDataTableTicket')->name('ticket.index.lists');

    Route::get('ticket/send/{ticket}', 'TicketController@send')->name('ticket.send');
    Route::post('ticket/send/data', 'TicketController@sendData')->name('ticket.send.data');

    Route::get('request', 'RequestController@index')->name('request.index');
    Route::get('request/list', 'RequestController@showDataTableRequest')->name('request.list');

    Route::get('request/{request}', 'RequestController@officeSend')->name('request.offuce.send');
    Route::post('request/{model_request}', 'RequestController@officeSendSave')->name('request.offuce.save');

    Route::resource('office', 'OfficeController');
    Route::get('office-list', 'OfficeController@showDataTable')->name('office.list');

    Route::get('log', 'LogController@index')->name('log.index');
    Route::get('log-list', 'LogController@showDataTable')->name('log.list');

    Route::get('export', 'LogController@export')->name('log.export');

});

Route::namespace('User')->prefix('user')->name('user.')->middleware('authDefaultDriver')->group(function () {

    Route::get('order/callback/{id}', 'PackageController@callback')->name('order.callback');

    Route::get('order/index', 'OrderController@index')->name('order.index');
    Route::get('order/list', 'OrderController@showDataTableOrder')->name('order.list');

    Route::get('package', 'PackageController@index')->name('package');
    Route::post('package/buy/{package}', 'PackageController@packageBuy')->name('package.buy');

    Route::get('favorite', 'RequestController@favorite')->name('favorite.index');
    Route::get('favorite/list', 'RequestController@showDataTableFavorite')->name('favorite.list');

    Route::get('block', 'RequestController@block')->name('block.index');
    Route::get('block/list', 'RequestController@showDataTableBlock')->name('block.list');
    Route::get('block/delete/{block}', 'RequestController@blockDelete')->name('block.delete');

    Route::get('/', 'UserController@index')->name('index');
    Route::post('/enable/code', 'UserController@enableCode')->name('enable.code');

    Route::get('/info', 'UserController@infoUpdateForm')->name('info.update');
    Route::post('/info', 'UserController@infoSave')->name('info.save');

    Route::get('/setting', 'UserController@setting')->name('setting');
    Route::post('/reset', 'UserController@resetPassword')->name('password.reset');

    Route::get('spouse', 'SpouseController@index')->name('spouse');

    Route::get('spouse/list', 'SpouseController@showDataTable')->name('spouse.list');

    Route::get('{user}', 'SpouseController@userShow')->name('show');

    Route::post('request/{user}', 'SpouseController@userRequest')->name('user.request');

    Route::post('user/request/like', 'SpouseController@userRequestLike')->name('request.like');

    Route::post('user/block/{user}', 'SpouseController@userBlock')->name('block');

    Route::post('user/report', 'SpouseController@userReport')->name('report');

    Route::get('request/get', 'RequestController@requestGet')->name('request.get');
    Route::get('request/get/list', 'RequestController@showDataTableRequestGet')->name('request.get.list');

    Route::get('request/send', 'RequestController@requestSend')->name('request.send');


    Route::get('request/send', 'RequestController@requestSend')->name('request.send');
    Route::get('request/send/list', 'RequestController@showDataTableRequestSend')->name('request.send.list');

    Route::get('ticket/index', 'TicketController@index')->name('ticket.index.list');
    Route::get('ticket/list', 'TicketController@showDataTableTicket')->name('ticket.index.lists');

    Route::get('ticket/send/{ticket?}', 'TicketController@send')->name('ticket.send');
    Route::post('ticket/send/data', 'TicketController@sendData')->name('ticket.send.data');
});


Route::namespace('Office')->prefix('office')->name('office.')->middleware('authDefaultDriver')->group(function () {

    Route::get('/', 'OfficeController@index')->name('index');

    Route::get('info', 'OfficeController@info')->name('info');

app/Http/Controllers/Admin/TicketController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Components\MyKavenegar;
use App\Http\Controllers\Controller;
use App\Model\Ticket;
use Hekmatinasser\Verta\Facades\Verta;
use Illuminate\Http\Request;

class TicketController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('admin.auth');
    }

    public function index()
    {
        return view('admin.ticket.index');
    }

    public function showDataTableTicket(Request $request)
    {
        $tikets = Ticket::where('parent_id', null)->latest();

        return datatables()->eloquent($tikets)
            ->editColumn('status', function ($tikets) {
                $result = '';
                if ($tikets->status == Ticket::STATUS_USER_RESPONSE) {
                    $result = '<span class="text-info">پاسخ کاربر</span>';
                } else if ($tikets->status == Ticket::STATUS_ADMIN_RESPONSE) {
                    $result = '<span class="text-warning">پاسخ مدیر</span>';
                } else if ($tikets->status == Ticket::STATUS_CLOSED_TICKET) {
                    $result = '<span class="text-success">بسته شده</span>';
                }
                return $result;
            })
            ->editColumn('created_at', function ($tikets) {
                return Verta($tikets->created_at)->format('Y/m/d H:i');
            })
            ->addColumn('action', function ($tikets) {
                return '<a href="' . route('admin.ticket.send', $tikets) . '" class="text-success">پاسخ</a>';
            })
            ->rawColumns(['action' => 'action', 'status' => 'status'])
            ->make(true);
    }

    public function send(Ticket $ticket)
    {
        $tickets = Ticket::where('parent_id', $ticket->id)->get();
        return view('admin.ticket.send', compact('ticket', 'tickets'));
    }

    public function sendData(Request $request)
    {
        $ticket_parent = Ticket::where('id', $request->ticket)->first();
        if ($ticket_parent) {
            $ticket = new Ticket();
            $ticket->user_id = $ticket_parent->user_id;
            $ticket->admin_id = auth('admin')->user()->id;
            $ticket->parent_id = $request->ticket;
            $ticket->content = $request->message;
            $ticket->status = '1';
            if ($ticket->save()) {
                Ticket::where('id', $request->ticket)->update(['status' => '1']);

                MyKavenegar::instance()->lookup($request->user->mobile, 'جواب تیکت', null, null, 'ezdsignup');

                return back();
            }
        }
        return back();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserAdminCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Model\City;
use App\Model\User;
use Hash;
use Illuminate\Auth\AuthManager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use Str;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('admin.auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.index');
    }

    public function showDataTable(Request $request)
    {

        $user = User::with('city')->select('users.*');

        return datatables()->eloquent($user)
            ->addColumn('action', function (User $user) {
                return '<a href="' . route('admin.user.show', $user) . '">مشاهده</a>';
            })
            ->rawColumns(['action' => 'action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::with('cities')->where('parent_id', null)->get();

        return view('admin.user.create', compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserAdminCreateRequest $request)
    {

        $data = [];
        foreach ($request->all() as $key => $value) {
            if($key == 'password'){
                $data[$key] = Hash::make($value);
                continue;
            }
            $data[$key] = strip_tags($value);
        }

        $data['dowry_cash'] = 0;
        $data['child'] = 0;

        if (User::create($data)) {

            return redirect()->route('admin.user.index')->with('success', trans('message.success_created'));
        }

        return back()->with('warning', trans('message.error_create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $cities = City::with('cities')->where('parent_id', null)->get();

        return view('admin.user.show', compact('user', 'cities'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserAdminCreateRequest $request, User $user)
    {

        $user = User::findOrFail($user->id);

        $user->gender = $request->gender;

        if ($user->update($request->all())) {

            return back()->with('success', trans('message.success_updated'));
        }

        return back()->with('error', trans('message.error_update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect('admin.user.index');
    }
}

resources/views/user/ticket/index.blade.php
@extends('layouts.user')

@section('title','تیکت ها')

@section('content')

<!-- Task manager table -->
<div class="card p-1">
    <div class="card-header bg-transparent header-elements-inline mb-1">
    <h6 class="card-title">تیکت ها <span class="text-success"><a href="{{ route('user.ticket.send') }}"><i class="icon-plus-circle2"></i></a></span></h6>
    </div>

    <table class="table tasks-list table-lg" id="laravel_datatable">
        <thead>
            <tr>
                <th>شماره</th>
                <th>نام ادمین</th>
                <th>زمان</th>
                {{-- <th>تعداد</th>
                <th>زمان</th>
                <th>وضعیت</th> --}}
                <th class="text-muted"><i class="icon-gear"></i></th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<!-- /task manager table -->

@endsection

@push('script')

<script src="/js/data_table/jquery.dataTables.min.js"></script>

<script>
    $(document).ready( function () {
            $('#laravel_datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('user.ticket.index.lists') }}",
                language: { "url": "/json/persian.json" },
                order: [1,'asc'],
                pageLength: 15,
                columns: [
                            { data: 'id', name: 'id' },
                            { data: 'status', name: 'status' },
                            { data: 'created_at', name: 'created_at' },
                            // { data: 'count', name: 'count' },
                            // { data: 'created_at', name: 'created_at' },
                            { data: 'action', name: 'action' },
                        ]
                });
            });
</script>
@endpush

resources/views/user/ticket/send.blade.php
@extends('layouts.user')

@section('title','تیکت')

@section('content')

@php
use Hekmatinasser\Verta\Facades;

$id = isset($ticket->id) ? $ticket->id : null;
@endphp
<!-- Task manager table -->
<!-- Main charts -->
<div class="row">


    <div class="card col-md-12 pb-3">

        <div class="card-header header-elements-inline">
            <legend>
                {{-- <h5 class="card-title text-left">پروفایل {{ $user->nick_name . ' ' . $age }} ساله</h5> --}}
            </legend>

            <legend>
                {{-- <h5 class="card-title text-right">آخری }}</h5> --}}
            </legend>
        </div>

        <div class="card-body">
            <ul class="media-list media-chat media-chat-scrollable mb-3">


                @isset($ticket)
                <li class="media">
                    <div class="mr-3">
                        <a href="../../../../global_assets/images/placeholders/placeholder.jpg" dideo-checked="true">
                            <img src="../../../../global_assets/images/placeholders/placeholder.jpg"
                                class="rounded-circle" alt="" width="40" height="40">
                        </a>
                    </div>

                    <div class="media-body">
                        <div class="media-chat-item">{{ $ticket->content }}</div>
                        <div class="font-size-sm text-muted mt-2">{{ Verta($ticket->created_at)->format('Y/m/d H:i') }}
                            <a href="#" dideo-checked="true"><i class="icon-pin-alt ml-2 text-muted"></i></a></div>
                    </div>
                </li>
                @endisset

                @isset($tickets)

                @foreach ($tickets as $ticket)
                @if ($ticket->status == \App\Model\Ticket::STATUS_USER_RESPONSE)
                <li class="media">
                    <div class="mr-3">
                        <a href="../../../../global_assets/images/placeholders/placeholder.jpg" dideo-checked="true">
                            <img src="../../../../global_assets/images/placeholders/placeholder.jpg"
                                class="rounded-circle" alt="" width="40" height="40">
                        </a>
                    </div>

                    <div class="media-body">
                        <div class="media-chat-item">{{ $ticket->content }}</div>
                        <div class="font-size-sm text-muted mt-2">{{ Verta($ticket->created_at)->format('Y/m/d H:i') }}
                            <a href="#" dideo-checked="true"><i class="icon-pin-alt ml-2 text-muted"></i></a></div>
                    </div>
                </li>
                @elseif ($ticket->status == \App\Model\Ticket::STATUS_ADMIN_RESPONSE)

                <li class="media media-chat-item-reverse">
                    <div class="media-body">
                        <div class="media-chat-item">{{ $ticket->content }}</div>
                        <div class="font-size-sm text-muted mt-2">{{ Verta($ticket->created_at)->format('Y/m/d H:i') }}
                            <a href="#" dideo-checked="true"><i class="icon-pin-alt ml-2 text-muted"></i></a></div>
                    </div>

                    <div class="ml-3">
                        <a href="../../../../global_assets/images/placeholders/placeholder.jpg" dideo-checked="true">
                            <img src="../../../../global_assets/images/placeholders/placeholder.jpg"
                                class="rounded-circle" alt="" width="40" height="40">
                        </a>
                    </div>
                </li>
                @endif
                @endforeach

                @endisset
            </ul>

            <form action="{{ route('user.ticket.send.data') }}" method="POST">
                @csrf
                <input type="hidden" name="ticket" value="{{ $id }}">
                <textarea name="message" class="form-control mb-3" rows="3" cols="1"
                    placeholder="پیام خود را وارد کنید ..."></textarea>

                <div class="d-flex align-items-center">
                    <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right ml-auto"><b><i
                                class="icon-paperplane"></i></b> ارسال</button>
                </div>
            </form>

        </div>
    </div>
</div>
<!-- /task manager table -->

@endsection