routes/web.php
<?php

use App\Model\Admin;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Spatie\Activitylog\Models\Activity;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// dd(Auth::guard('admin')->check());
// 




Route::get('/', function () {

    return Activity::all()->last();


    // Admin::create([
    //     'name' => 'faraz',
    //     'email' => 'admin@gmail.com',
    //     'password' => Hash::make(123456789),
    // ]);

    // User::create([
    //     'nick_name' => 'ali reza',
    //     'mobile' => '09357589031',
    //     'gender' => 1,
    //     'password' =>Hash::make(123456)
    // ]);
    return view('welcome');
});


// Auth::routes();

Route::namespace('Auth')->group(function () {

    // activity()->log('Look mum, I logged something')->su;

    Route::get('/admin/login', 'LoginController@showAdminLoginForm')->name('admin.login.form');
    Route::get('/user/login', 'LoginController@showUserLoginForm')->name('user.login.form');
    Route::get('/office/login', 'LoginController@showOfficeLoginForm')->name('office.login.form');

    // Route::get('/user/signup', 'RegisterController@showRegistrationForm')->name('user.signup.form');

    Route::post('/admin/login', 'LoginController@adminLogin')->name('admin.login');
    Route::post('/user/login', 'LoginController@userLogin')->name('user.login');
    Route::post('/office/login', 'LoginController@officeLogin')->name('office.login');

    Route::get('/admin/logout', 'LoginController@adminLogout')->name('admin.logout');
    Route::get('/user/logout', 'LoginController@userLogout')->name('user.logout');
    Route::get('/office/logout', 'LoginController@officeLogout')->name('office.logout');

    Route::get('/office/signup', 'RegisterController@showOfficeRegistrationForm')->name('office.signup');

    // Route::post('/register/admin', 'RegisterController@createAdmin');
    Route::post('/signup', 'RegisterController@register')->name('user.signup');
    Route::post('/office/signup', 'RegisterController@officeRegister')->name('office.signup');


    Route::get('/password/reset', 'ResetPasswordController@showResetForm')->name('password.request');
    Route::post('/password/update', 'ResetPasswordController@reset')->name('password.update');

    Route::get('/token/reset/{mobile}', 'ResetPasswordController@showTokenForm')->name('password.reset.token');
    Route::post('/token/update', 'ResetPasswordController@tokenConfirmed')->name('password.update.token')->middleware('throttle:5|1');



    // Route::view('/home', 'home')->middleware('auth');

    // Route::view('/admin/dashboard', 'admin')->name('admin.');
    // Route::view('/writer', 'writer');


});


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('authDefaultDriver')->group(function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::get('/setting', 'AdminController@setting')->name('setting');
    Route::post('/reset', 'AdminController@resetPassword')->name('password.reset');

    Route::resource('user', 'UserController');
    Route::get('users', 'UserController@showDataTable')->name('user.list');

    Route::get('financial/all', 'AdminController@financialAll')->name('financial.all');

    Route::get('financial/success', 'AdminController@financialSuccess')->name('financial.success');
    Route::get('financial/success/list', 'AdminController@showDataTableFinancialSuccess')->name('financial.success.list');

    Route::get('financial/fail', 'AdminController@financialFail')->name('financial.fail');
    Route::get('financial/fail/list', 'AdminController@showDataTableFinancialFail')->name('financial.fail.list');

    Route::get('alert/index', 'AlertController@index')->name('alert.index');
    Route::get('alert/list', 'AlertController@showDataTableAlert')->name('alert.list');
    Route::get('alert/create', 'AlertController@create')->name('alert.create');
    Route::post('alert/store', 'AlertController@store')->name('alert.store');
    Route::get('alert/destroy/{alert}', 'AlertController@destroy')->name('alert.destroy');

    Route::resource('admins', 'AdminManagerController');
    Route::get('admins-list', 'AdminManagerController@showDataTable')->name('admins.list');

    Route::get('admins/permission/{admin}', 'AdminManagerController@permission')->name('admins.permission');
    Route::post('admins/permission/{admin}', 'AdminManagerController@permissionUpdate')->name('admins.permission');

    Route::get('reports', 'ReportController@index')->name('report.index');
    Route::get('report-list', 'ReportController@showDataTable')->name('report.list');

    Route::get('blocks', 'BlockController@index')->name('block.index');
    Route::get('block-list', 'BlockController@showDataTable')->name('block.list');

    Route::get('admin/blocks', 'BlockController@adminBlockIndex')->name('admin.block');
    Route::get('admin/block-list', 'BlockController@adminBlockShowDataTable')->name('admin.block.list');
    Route::get('admin/block/delete/{user}', 'BlockController@adminBlockDelete')->name('admin.block.delete');

    Route::post('admin/blocks/add/{user}', 'BlockController@adminBlockAdd')->name('admin.block.add');

    Route::resource('package', 'PackageController');


    Route::get('config', 'ConfigController@index')->name('config');
    Route::post('config', 'ConfigController@update')->name('config.update');


    Route::get('ticket/index', 'TicketController@index')->name('ticket.index.list');
    Route::get('ticket/list', 'TicketController@showDataTableTicket')->name('ticket.index.lists');

    Route::get('ticket/send/{ticket}', 'TicketController@send')->name('ticket.send');
    Route::post('ticket/send/data', 'TicketController@sendData')->name('ticket.send.data');

    Route::get('request', 'RequestController@index')->name('request.index');
    Route::get('request/list', 'RequestController@showDataTableRequest')->name('request.list');

    Route::get('request/{request}', 'RequestController@officeSend')->name('request.offuce.send');
    Route::post('request/{model_request}', 'RequestController@officeSendSave')->name('request.offuce.save');

    Route::resource('office', 'OfficeController');
    Route::get('office-list', 'OfficeController@showDataTable')->name('office.list');

    Route::get('log', 'LogController@index')->name('log.index');
    Route::get('log-list', 'LogController@showDataTable')->name('log.list');

    Route::get('export', 'LogController@export')->name('log.export');

});

Route::namespace('User')->prefix('user')->name('user.')->middleware('authDefaultDriver')->group(function () {

    Route::get('order/callback/{id}', 'PackageController@callback')->name('order.callback');

    Route::get('order/index', 'OrderController@index')->name('order.index');
    Route::get('order/list', 'OrderController@showDataTableOrder')->name('order.list');

    Route::get('package', 'PackageController@index')->name('package');
    Route::post('package/buy/{package}', 'PackageController@packageBuy')->name('package.buy');

    Route::get('favorite', 'RequestController@favorite')->name('favorite.index');
    Route::get('favorite/list', 'RequestController@showDataTableFavorite')->name('favorite.list');

    Route::get('block', 'RequestController@block')->name('block.index');
    Route::get('block/list', 'RequestController@showDataTableBlock')->name('block.list');
    Route::get('block/delete/{block}', 'RequestController@blockDelete')->name('block.delete');

    Route::get('/', 'UserController@index')->name('index');
    Route::post('/enable/code', 'UserController@enableCode')->name('enable.code');

    Route::get('/info', 'UserController@infoUpdateForm')->name('info.update');
    Route::post('/info', 'UserController@infoSave')->name('info.save');

    Route::get('/setting', 'UserController@setting')->name('setting');
    Route::post('/reset', 'UserController@resetPassword')->name('password.reset');

    Route::get('spouse', 'SpouseController@index')->name('spouse');

    Route::get('spouse/list', 'SpouseController@showDataTable')->name('spouse.list');

    Route::get('{user}', 'SpouseController@userShow')->name('show');

    Route::post('request/{user}', 'SpouseController@userRequest')->name('user.request');

    Route::post('user/request/like', 'SpouseController@userRequestLike')->name('request.like');

    Route::post('user/block/{user}', 'SpouseController@userBlock')->name('block');

    Route::post('user/report', 'SpouseController@userReport')->name('report');

    Route::get('request/get', 'RequestController@requestGet')->name('request.get');
    Route::get('request/get/list', 'RequestController@showDataTableRequestGet')->name('request.get.list');

    Route::get('request/send', 'RequestController@requestSend')->name('request.send');


    Route::get('request/send', 'RequestController@requestSend')->name('request.send');
    Route::get('request/send/list', 'RequestController@showDataTableRequestSend')->name('request.send.list');

    Route::get('ticket/index', 'TicketController@index')->name('ticket.index.list');
    Route::get('ticket/list', 'TicketController@showDataTableTicket')->name('ticket.index.lists');

    Route::get('ticket/send/{ticket?}', 'TicketController@send')->name('ticket.send');
    Route::post('ticket/send/data', 'TicketController@sendData')->name('ticket.send.data');
});


Route::namespace('Office')->prefix('office')->name('office.')->middleware('authDefaultDriver')->group(function () {

    Route::get('/', 'OfficeController@index')->name('index');

    Route::get('info', 'OfficeController@info')->name('info');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserAdminCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Model\City;
use App\Model\User;
use Hash;
use Illuminate\Auth\AuthManager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use Str;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('admin.auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.index');
    }

    public function showDataTable(Request $request)
    {

        $user = User::with('city')->select('users.*');

        return datatables()->eloquent($user)
            ->addColumn('action', function (User $user) {
                return '<a href="' . route('admin.user.show', $user) . '">مشاهده</a>';
            })
            ->rawColumns(['action' => 'action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::with('cities')->where('parent_id', null)->get();

        return view('admin.user.create', compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserAdminCreateRequest $request)
    {

        $data = [];
        foreach ($request->all() as $key => $value) {
            if($key == 'password'){
                $data[$key] = Hash::make($value);
                continue;
            }
            $data[$key] = strip_tags($value);
        }

        $data['dowry_cash'] = 0;
        $data['child'] = 0;

        if (User::create($data)) {

            return redirect()->route('admin.user.index')->with('success', trans('message.success_created'));
        }

        return back()->with('warning', trans('message.error_create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $cities = City::with('cities')->where('parent_id', null)->get();

        return view('admin.user.show', compact('user', 'cities'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserAdminCreateRequest $request, User $user)
    {

        $user = User::findOrFail($user->id);

        $user->gender = $request->gender;

        if ($user->update($request->all())) {

            return back()->with('success', trans('message.success_updated'));
        }

        return back()->with('error', trans('message.error_update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect('admin.user.index');
    }
}

app/Http/Controllers/User/OrderController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Model\Order;
use Hekmatinasser\Verta\Facades\Verta;
use Illuminate\Http\Request;

class OrderController extends Controller
{


    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('user.auth');
    }


    public function index()
    {
        return view('user.order.index');
    }


    public function showDataTableOrder(Request $request)
    {
        $order = Order::where('user_id', auth('user')->user()->id)->latest();

        return datatables()->eloquent($order)
            ->editColumn('status', function ($order) {
                $result = '';
                if ($order->status == Order::STATUS_FAILED) {
                    $result = '<span class="text-danger">ناموفق</span>';
                } else if ($order->status == Order::STATUS_WATING) {
                    $result = '<span class="text-warning">منتظر</span>';
                } else if ($order->status == Order::STATUS_SUCCESS) {
                    $result = '<span class="text-success">موفق</span>';
                }
                return $result;
            })
            ->editColumn('created_at', function ($order) {
                return Verta($order->created_at)->format('Y/m/d - H:i');
            })
            // ->addColumn('action', function (Block $order) {
            //     return '<a href="' . route('user.block.delete', $order) . '" class="text-danger">حذف از مسدود</a>';
            // })
            ->rawColumns(['status' => 'status'])
            ->make(true);
    }
}

app/Http/Controllers/User/PackageController.php
<?php

namespace App\Http\Controllers\User;

use App\Components\ZarinPal;
use App\Http\Controllers\Controller;
use App\Model\Order;
use App\Model\Package;
use Illuminate\Http\Request;

class PackageController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('user.auth');
    }

    
    public function index()
    {
        // return redirect('https://www.google.com');

        $pakages = Package::all();
        return view('user.package.index', compact('pakages'));
    }

    public function packageBuy(Package $package)
    {
        $order = new Order();
        $order->user_id = auth('user')->user()->id;
        $order->package_id = $package->id;
        $order->price = $package->price;
        $order->count = $package->count;
        $order->save();

        $zarinPal = new ZarinPal($order);

        return redirect($zarinPal->purchase());
    }

    public function callback(Request $request, $id)
    {
        $order = Order::where('id', decrypt($id))->where('user_id', auth('user')->user()->id)->first();

        if ($request->Status != 'OK') {
            $order->status = Order::STATUS_FAILED;
            $order->save();
            return redirect()->route('user.order.index')->with('error', trans('message.payment_failed'));
        }

        $zarinPal = new ZarinPal($order);
        $ref = $zarinPal->verify($request->Authority);

        if (!$ref) {
            $order->status = Order::STATUS_FAILED;
            $order->save();
            return redirect()->route('user.order.index')->with('error', trans('message.payment_failed'));
        }

        $order->ref_id = $ref;
        $order->status = Order::STATUS_SUCCESS;

        if($order->save()){
            $order->user->sms_count = $order->user->sms_count + $order->count;
            $order->user->save();
        }
        return redirect()->route('user.order.index')->with('success', trans('message.payment_success'));
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('title','داشبورد')

@section('content')


<!-- Main charts -->
<div class="row">


    <div class="card">

        <div class="card-header header-elements-inline">
            <legend>
                <h5 class="card-title">اطلاعات شخصی</h5>
            </legend>
        </div>
        <div class="card-body">

            <form action="{{ route('admin.user.store') }}" method="POST" enctype="multipart/form-data">

                @csrf

                <p class="mb-10">
                    فرم اطلاعات خود را کامل کنید. در غیر اینصورت نمی توانید از امکانات سایت استفاده کنید.
                </p>

                <fieldset class="mb-3">

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">اسم مستعار</label>
                        <div class="col-lg-9">
                            <input type="text" name="nick_name" class="form-control">
                            @error('nick_name')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">تلفن همراه</label>
                        <div class="col-lg-9">
                            <input type="text" name="mobile" class="form-control">
                            <span class="text-warning">اخطار: در صورت تغییر شماره تلفن همراه باید فعال سازی
                                کنید.</span><br>
                            @error('mobile')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">آپلود عکس</label>
                        <div class="col-lg-9">
                            <input type="file" name="image" class="form-control-uniform-custom">
                            @error('image')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">جنسیت</label>
                        <div class="col-lg-9">
                            
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="female" value="0"
                                    checked>
                                <label class="form-check-label pr-4" for="female">
                                    خانم
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="man" value="1">
                                <label class="form-check-label pr-4" for="man">
                                    آقا
                                </label>
                            </div>
                            @error('gender')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">شهر زندگی</label>
                        <div class="col-lg-9">
                            <select name="city_id" class="form-control">
                                @foreach ($cities as $city)
                                <optgroup label="{{ $city->name }}">
                                    @foreach ($city->cities as $c)
                                    <option value="{{ $c->id }}">
                                        {{ $c->name }}
                                    </option>
                                    @endforeach
                                </optgroup>
                                @endforeach
                            </select>
                            @error('city_id')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">سن</label>
                        <div class="col-lg-9">
                            <input type="text" name="age" class="form-control" data-mask="1999/99/99"
                                style="direction: ltr">
                            <span class="text-warning">فرمت صحیح: 1371/02/08</span><br>
                            @error('age')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">وضعیت ازدواج</label>
                        <div class="col-lg-9">
                            <select name="marital_status" class="form-control">
                                @foreach (App\Model\User::MARITAL_STATUS_LIST as $key => $marital_status)

                                <option value="{{ $key }}">
                                    {{ $marital_status }}
                                </option>
                                @endforeach
                            </select>
                            @error('marital_status')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">قد</label>
                        <div class="col-lg-9">
                            <input type="text" name="height" class="form-control">
                            <span class="text-info">واحد شمارش سانتی متر است.</span><br>
                            @error('height')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">وزن</label>
                        <div class="col-lg-9">
                            <input type="text" name="weight" class="form-control">
                            @error('weight')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">تحصیلات</label>
                        <div class="col-lg-9">
                            <select name="education" class="form-control">
                                @foreach (App\Model\User::EDUCATION_LIST as $key => $education)

                                <option value="{{ $key }}">
                                    {{ $education }}
                                </option>
                                @endforeach
                            </select>
                            @error('education')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">محل اقامت</label>
                        <div class="col-lg-9">
                            <select name="residence" class="form-control">
                                @foreach (App\Model\User::RESIDENCE_STATUS_LIST as $key => $residence)

                                <option value="{{ $key }}">
                                    {{ $residence }}
                                </option>
                                @endforeach
                            </select>
                            @error('residence')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">وضعیت اشتغال</label>
                        <div class="col-lg-9">
                            <select name="employment_status" class="form-control">
                                @foreach (App\Model\User::EMPLOYMENT_STATUS_LIST as $key => $employment)

                                <option value="{{ $key }}">
                                    {{ $employment }}
                                </option>
                                @endforeach
                            </select>
                            @error('employment_status')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">عقاید مذهبی</label>
                        <div class="col-lg-9">
                            <select name="religious" class="form-control">
                                @foreach (App\Model\User::RELIGIOUS_LIST as $key => $religious)

                                <option value="{{ $key }}">
                                    {{ $religious }}
                                </option>
                                @endforeach
                            </select>
                            @error('religious')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">نوع مهریه</label>
                        <div class="col-lg-9">
                            <select name="dowry" class="form-control">
                                @foreach (App\Model\User::DOWRY_LIST as $key => $dowry)

                                <option value="{{ $key }}">
                                    {{ $dowry }}
                                </option>
                                @endforeach
                            </select>
                            @error('dowry')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">میزان مهریه</label>
                        <div class="col-lg-9">
                            <input type="text" name="dowry_cash" class="form-control">
                            <span class="text-info">واحد تومان است.</span><br>
                            @error('dowry_cash')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">تعداد فرزند</label>
                        <div class="col-lg-9">
                            <input type="text" name="child" class="form-control">
                            @error('child')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">توضیح خلاصه از خود</label>
                        <div class="col-lg-9">
                            <textarea type="text" name="story" class="form-control" rows="6"></textarea>
                            @error('story')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-lg-3">رمز عبور</label>
                        <div class="col-lg-9">
                            <input type="password" name="password" class="form-control">
                            @error('password')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                </fieldset>
                <div class="text-right">
                    <button type="submit" class="btn btn-success">ذخیره <i class="icon-paperplane ml-2"></i></button>
                </div>

            </form>
        </div>
    </div>


</div>

<!-- /main charts -->

@endsection